spring.application.name=chatbot

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3:4b
spring.ai.ollama.chat.options.temperature=0

spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.name=mcp-chatbot